version: '3'
services:
  api:
    build: .
    command: python manage.py runserver localhost:8000
    container_name: dpg_api
    volumes:
      - .:/docker_polls_group/
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
