version: '3.7'

services:
  postgres:
    container_name: "postgresql"
    image: postgres:12
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: Admin123!
        POSTGRES_USER: admin
        POSTGRES_DB: postgresql

  api:
    build: ./api
    container_name: "dpg_api"
    volumes:
      - ./api:/opt/docker_polls_group/api
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - postgres
    command: gunicorn --reload wsgi:application -w 2 -b :8000 -t 120

